### PR TITLE
Use KEY_HOMEPAGE for guide button

### PR DESCRIPTION
**Pull request by transcengopher**
Like it says in https://github.com/medusalix/xow/issues/129, replaced BTN_MODE with KEY_HOMEPAGE.

### CODE REVIEW

**Comment by transcengopher** [comment]
Sorry, that was me trying to learn how to undo stuff. I didn't intend to pull before I test that it works.

**Comment by kakra** [comment]
You can mark the PR as a draft.

**Comment by transcengopher** [comment]
@kakra, I could.
However, actually testing this stuff - with KEY_HOMEPAGE, pressing the guide button, for example, no longer opens the Steam Big Picture mode. I'm guessing this would be one of quite long list of issues that will emerge after this commit.

Considering above, I'm content with canning this PR altogether, unless there's something else that I can try to address whatever was not quite working with XSeries controllers.

Mind you, I don't have that one, I have the 1708 wireless.

**Comment by kakra** [comment]
Yeah, I can confirm that for xpadneo: Something must have changed in other packages or Steam itself that it no longer recognizes `KEY_HOMEPAGE` to show Steam and switch to Big Picture mode. I'm currently in the process of splitting xpadneo into subdevices where the Guide button will have its own input device, I think that might bring the functionality back. I'll report back here with my findings.

**Pull request closed without merging**
