### PR TITLE
Fix website install section, improve performance

### PR DESCRIPTION
**Pull request by cristianovitorino**
Fixed the website broken install section, also improved the aesthetics of it. Improved website performance by leaving  all the files in their minified version.

### CODE REVIEW

**Comment by medusalix** [comment]
It looks like the PR only catched your previous changes/commits. You might want to check on that.

**Comment by cristianovitorino** [comment]
> It looks like the PR only catched your previous changes/commits. You might want to check on that.

Weird. Let me check.

**Comment by medusalix** [comment]
Thanks for your continuous work on the website 😃.
Two quick notes:

- I've changed the website's title from `Xow` to `xow` to match the project's name.
- People might try to copy the text from the instructions to their clipboard and will fail to do so because the text selection color is *very* hard to see. Bootstrap's default is apparently `white`.

It would be nice if you could submit future PRs from a dedicated branch of your fork. It makes the version control much easier as only the related commits are shown.

**Comment by cristianovitorino** [comment]
> Thanks for your continuous work on the website .

No problem, has been fun : )

> Two quick notes:
> 
> * I've changed the website's title from `Xow` to `xow` to match the project's name.

OK.

> * People might try to copy the text from the instructions to their clipboard and will fail to do so because the text selection color is _very_ hard to see. Bootstrap's default is apparently `white`.
> 

Yeah, gonna look into that.

> It would be nice if you could submit future PRs from a dedicated branch of your fork. It makes the version control much easier as only the related commits are shown.

Sure. I've made a "website" branch.

**Comment by estatra** [comment]
Hey @medusalix Just letting you know I recently changed my account name and link. I might update the website and PR to reflect the change, for current and future credit you can just use "Atra", all my links are updated.

**Pull request merged**
