### PR TITLE
Basic rpm build instructions

### PR DESCRIPTION
**Pull request by Yajo**
This builds for Fedora 32/rawhide, and you can install it directly from https://copr.fedorainfracloud.org/coprs/yajo/xow/

I guess the best place to store this file is here.

### CODE REVIEW

**Comment by medusalix** [comment]
Microsoft's license agreement unfortunately doesn't allow me/you to distribute any binaries of xow on the internet. The dongle's firmware is embedded in the resulting executable when you run `make`. This won't change unless Microsoft gives me the explicit permission to redistribute their firmware.

**Comment by Yajo** [comment]
Oh ok then I'll remove the repo.In any case, it makes even more useful to have a spec. For rpm-ostree based distros like fedora sulverblue this is the only way to install xow.This way I can download the repo and build the spec more easily. Don't you think?Enviado de Samsung Mobile
-------- Mensaje original --------De: Severin <notifications@github.com> Fecha: 5/6/20  17:24  (GMT+00:00) Para: medusalix/xow <xow@noreply.github.com> Cc: Jairo Llopis <yajo.sk8@gmail.com>, Author <author@noreply.github.com> Asunto: Re: [medusalix/xow] Basic rpm build instructions (#81) 
Microsoft's license agreement unfortunately doesn't allow me/you to distribute any binaries of xow on the internet. The dongle's firmware is embedded in the resulting executable when you run make. This won't change unless Microsoft gives me the explicit permission to redistribute their firmware.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/medusalix/xow/pull/81#issuecomment-639609625",
"url": "https://github.com/medusalix/xow/pull/81#issuecomment-639609625",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Yajo** [comment]
OK, makes sense, here it is then: https://gitlab.com/yajoman/xow-rpm

**Comment by medusalix** [comment]
Is that a public repository? I get a `Page not found` error when clicking on that link.

**Comment by Yajo** [comment]
Oops it seems I forgot to publish it. Check it now.

**Comment by medusalix** [comment]
I've added it to the README. Thank you :smiley:.

**Pull request closed without merging**
